### ISSUE TITLE
Error in importing grss

### ISSUE THREAD

**Issue by Pachacoti** [rahil-makadia/grss#40]
While the installation went smoothly, I encountered the following error when I
`import grss`
in `python3`:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mthui/Software/anaconda3/lib/python3.9/site-packages/grss/__init__.py", line 2, in <module>
    from . import fit
  File "/home/mthui/Software/anaconda3/lib/python3.9/site-packages/grss/fit/__init__.py", line 5, in <module>
    from .fit_simulation import *
  File "/home/mthui/Software/anaconda3/lib/python3.9/site-packages/grss/fit/fit_simulation.py", line 7, in <module>
    from .. import prop
  File "/home/mthui/Software/anaconda3/lib/python3.9/site-packages/grss/prop/__init__.py", line 2, in <module>
    from .prop_parallel import *
  File "/home/mthui/Software/anaconda3/lib/python3.9/site-packages/grss/prop/prop_parallel.py", line 5, in <module>
    from . import prop_simulation as prop
ImportError: cannot import name 'prop_simulation' from partially initialized module 'grss.prop' (most likely due to a circular import) (/home/mthui/Software/anaconda3/lib/python3.9/site-packages/grss/prop/__init__.py)
```
Any idea as to how to fix this?

**Comment by Pachacoti** [comment]
@rahil-makadia Initially indeed I did run `import grss` from the directory of the cloned repository. But this error still persists even if I `cd` to other randomly picked directories, with the only difference being the paths of the cloned repository replaced by the anaconda ones. To give you more context, this is the version of python on my machine:
```
Python 3.9.18 (main, Sep 11 2023, 13:41:44) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
```

**Comment by Pachacoti** [comment]
I can't even find the grss.prop subdirectory. Or do you mean grss/prop? If so indeed there is no prop_simulation. I've tried re-installed it but this didn't really help. To check whether there was any lurking error I did `$ python3 -m pip install --verbose`, and the returned messages are appended in the following:
```
Using pip 23.3.1 from /home/mthui/Software/anaconda3/lib/python3.9/site-packages/pip (python 3.9)
Processing /home/mthui/Software/grss/grss
  Running command pip subprocess to install build dependencies
  Collecting setuptools>=43.0.0
    Using cached setuptools-69.1.0-py3-none-any.whl.metadata (6.1 kB)
  Using cached setuptools-69.1.0-py3-none-any.whl (819 kB)
  Installing collected packages: setuptools
  ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
  conda-repo-cli 1.0.75 requires requests_mock, which is not installed.
  conda-repo-cli 1.0.75 requires clyent==1.2.1, but you have clyent 1.2.2 which is incompatible.
  Successfully installed setuptools-69.1.0
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  running egg_info
  creating grss.egg-info
  writing grss.egg-info/PKG-INFO
  writing dependency_links to grss.egg-info/dependency_links.txt
  writing requirements to grss.egg-info/requires.txt
  writing top-level names to grss.egg-info/top_level.txt
  writing manifest file 'grss.egg-info/SOURCES.txt'
  reading manifest file 'grss.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*' under directory 'extern/pybind11'
  adding license file 'LICENSE'
  writing manifest file 'grss.egg-info/SOURCES.txt'
  Getting requirements to build wheel ... done
  Running command pip subprocess to install backend dependencies
  Collecting wheel
    Using cached wheel-0.42.0-py3-none-any.whl.metadata (2.2 kB)
  Using cached wheel-0.42.0-py3-none-any.whl (65 kB)
  Installing collected packages: wheel
  Successfully installed wheel-0.42.0
  Installing backend dependencies ... done
  Running command Preparing metadata (pyproject.toml)
  running dist_info
  creating /tmp/pip-modern-metadata-1ln50xd3/grss.egg-info
  writing /tmp/pip-modern-metadata-1ln50xd3/grss.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-modern-metadata-1ln50xd3/grss.egg-info/dependency_links.txt
  writing requirements to /tmp/pip-modern-metadata-1ln50xd3/grss.egg-info/requires.txt
  writing top-level names to /tmp/pip-modern-metadata-1ln50xd3/grss.egg-info/top_level.txt
  writing manifest file '/tmp/pip-modern-metadata-1ln50xd3/grss.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-modern-metadata-1ln50xd3/grss.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*' under directory 'extern/pybind11'
  adding license file 'LICENSE'
  writing manifest file '/tmp/pip-modern-metadata-1ln50xd3/grss.egg-info/SOURCES.txt'
  creating '/tmp/pip-modern-metadata-1ln50xd3/grss-3.0.0.dist-info'
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: astropy>=5.0 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from grss==3.0.0) (5.3.4)
Requirement already satisfied: astroquery>=0.4.0 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from grss==3.0.0) (0.4.6)
Requirement already satisfied: basemap>=1.4.0 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from grss==3.0.0) (1.4.1)
Requirement already satisfied: healpy>=1.16.0 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from grss==3.0.0) (1.16.6)
Requirement already satisfied: joblib>=1.3.0 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from grss==3.0.0) (1.3.2)
Requirement already satisfied: matplotlib>=3.3.0 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from grss==3.0.0) (3.8.0)
Requirement already satisfied: numba>=0.55.0 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from grss==3.0.0) (0.59.0)
Requirement already satisfied: numpy>=1.22.0 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from grss==3.0.0) (1.22.4)
Requirement already satisfied: pandas>=1.5.0 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from grss==3.0.0) (2.1.4)
Requirement already satisfied: pybind11>=2.10.0 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from pybind11[global]>=2.10.0->grss==3.0.0) (2.11.1)
Requirement already satisfied: requests>=2.22.0 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from grss==3.0.0) (2.31.0)
Requirement already satisfied: spiceypy>=5.0.0 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from grss==3.0.0) (6.0.0)
Requirement already satisfied: pyerfa>=2.0 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from astropy>=5.0->grss==3.0.0) (2.0.0)
Requirement already satisfied: PyYAML>=3.13 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from astropy>=5.0->grss==3.0.0) (6.0.1)
Requirement already satisfied: packaging>=19.0 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from astropy>=5.0->grss==3.0.0) (23.1)
Requirement already satisfied: beautifulsoup4>=4.3.2 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from astroquery>=0.4.0->grss==3.0.0) (4.12.2)
Requirement already satisfied: html5lib>=0.999 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from astroquery>=0.4.0->grss==3.0.0) (1.1)
Requirement already satisfied: keyring>=4.0 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from astroquery>=0.4.0->grss==3.0.0) (23.13.1)
Requirement already satisfied: pyvo>=1.1 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from astroquery>=0.4.0->grss==3.0.0) (1.5)
Requirement already satisfied: basemap-data<1.4,>=1.3.2 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from basemap>=1.4.0->grss==3.0.0) (1.3.2)
Requirement already satisfied: pyshp<2.4,>=1.2 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from basemap>=1.4.0->grss==3.0.0) (2.3.1)
Requirement already satisfied: pyproj<3.7.0,>=1.9.3 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from basemap>=1.4.0->grss==3.0.0) (3.6.1)
Requirement already satisfied: scipy in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from healpy>=1.16.0->grss==3.0.0) (1.11.4)
Requirement already satisfied: contourpy>=1.0.1 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from matplotlib>=3.3.0->grss==3.0.0) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from matplotlib>=3.3.0->grss==3.0.0) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from matplotlib>=3.3.0->grss==3.0.0) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from matplotlib>=3.3.0->grss==3.0.0) (1.4.4)
Requirement already satisfied: pillow>=6.2.0 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from matplotlib>=3.3.0->grss==3.0.0) (10.2.0)
Requirement already satisfied: pyparsing>=2.3.1 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from matplotlib>=3.3.0->grss==3.0.0) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from matplotlib>=3.3.0->grss==3.0.0) (2.8.2)
Requirement already satisfied: importlib-resources>=3.2.0 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from matplotlib>=3.3.0->grss==3.0.0) (6.1.1)
Requirement already satisfied: llvmlite<0.43,>=0.42.0dev0 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from numba>=0.55.0->grss==3.0.0) (0.42.0)
Requirement already satisfied: pytz>=2020.1 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from pandas>=1.5.0->grss==3.0.0) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from pandas>=1.5.0->grss==3.0.0) (2023.3)
Requirement already satisfied: pybind11-global==2.11.1 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from pybind11[global]>=2.10.0->grss==3.0.0) (2.11.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from requests>=2.22.0->grss==3.0.0) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from requests>=2.22.0->grss==3.0.0) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from requests>=2.22.0->grss==3.0.0) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from requests>=2.22.0->grss==3.0.0) (2024.2.2)
Requirement already satisfied: soupsieve>1.2 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from beautifulsoup4>=4.3.2->astroquery>=0.4.0->grss==3.0.0) (2.5)
Requirement already satisfied: six>=1.9 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from html5lib>=0.999->astroquery>=0.4.0->grss==3.0.0) (1.16.0)
Requirement already satisfied: webencodings in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from html5lib>=0.999->astroquery>=0.4.0->grss==3.0.0) (0.5.1)
Requirement already satisfied: zipp>=3.1.0 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from importlib-resources>=3.2.0->matplotlib>=3.3.0->grss==3.0.0) (3.17.0)
Requirement already satisfied: jaraco.classes in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from keyring>=4.0->astroquery>=0.4.0->grss==3.0.0) (3.2.1)
Requirement already satisfied: importlib-metadata>=4.11.4 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from keyring>=4.0->astroquery>=0.4.0->grss==3.0.0) (7.0.1)
Requirement already satisfied: SecretStorage>=3.2 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from keyring>=4.0->astroquery>=0.4.0->grss==3.0.0) (3.3.1)
Requirement already satisfied: jeepney>=0.4.2 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from keyring>=4.0->astroquery>=0.4.0->grss==3.0.0) (0.7.1)
Requirement already satisfied: cryptography>=2.0 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from SecretStorage>=3.2->keyring>=4.0->astroquery>=0.4.0->grss==3.0.0) (41.0.7)
Requirement already satisfied: more-itertools in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from jaraco.classes->keyring>=4.0->astroquery>=0.4.0->grss==3.0.0) (10.1.0)
Requirement already satisfied: cffi>=1.12 in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from cryptography>=2.0->SecretStorage>=3.2->keyring>=4.0->astroquery>=0.4.0->grss==3.0.0) (1.16.0)
Requirement already satisfied: pycparser in /home/mthui/Software/anaconda3/lib/python3.9/site-packages (from cffi>=1.12->cryptography>=2.0->SecretStorage>=3.2->keyring>=4.0->astroquery>=0.4.0->grss==3.0.0) (2.21)
Building wheels for collected packages: grss
  Running command Building wheel for grss (pyproject.toml)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-cpython-39
  creating build/lib.linux-x86_64-cpython-39/grss
  copying grss/__init__.py -> build/lib.linux-x86_64-cpython-39/grss
  copying grss/utils.py -> build/lib.linux-x86_64-cpython-39/grss
  creating build/lib.linux-x86_64-cpython-39/grss/fit
  copying grss/fit/fit_radar.py -> build/lib.linux-x86_64-cpython-39/grss/fit
  copying grss/fit/fit_optical.py -> build/lib.linux-x86_64-cpython-39/grss/fit
  copying grss/fit/fit_utils.py -> build/lib.linux-x86_64-cpython-39/grss/fit
  copying grss/fit/fit_simulation.py -> build/lib.linux-x86_64-cpython-39/grss/fit
  copying grss/fit/__init__.py -> build/lib.linux-x86_64-cpython-39/grss/fit
  creating build/lib.linux-x86_64-cpython-39/grss/prop
  copying grss/prop/prop_unscented.py -> build/lib.linux-x86_64-cpython-39/grss/prop
  copying grss/prop/prop_utils.py -> build/lib.linux-x86_64-cpython-39/grss/prop
  copying grss/prop/prop_parallel.py -> build/lib.linux-x86_64-cpython-39/grss/prop
  copying grss/prop/__init__.py -> build/lib.linux-x86_64-cpython-39/grss/prop
  running egg_info
  writing grss.egg-info/PKG-INFO
  writing dependency_links to grss.egg-info/dependency_links.txt
  writing requirements to grss.egg-info/requires.txt
  writing top-level names to grss.egg-info/top_level.txt
  reading manifest file 'grss.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*' under directory 'extern/pybind11'
  adding license file 'LICENSE'
  writing manifest file 'grss.egg-info/SOURCES.txt'
  /tmp/pip-build-env-an6mypj5/overlay/lib/python3.9/site-packages/setuptools/command/build_py.py:207: _Warning: Package 'grss.debias' is absent from the `packages` configuration.
  !!

          ********************************************************************************
          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'grss.debias' as an importable package[^1],
          but it is absent from setuptools' `packages` configuration.

          This leads to an ambiguous overall configuration. If you want to distribute this
          package, please make sure that 'grss.debias' is explicitly added
          to the `packages` configuration field.

          Alternatively, you can also rely on setuptools' discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).

          You can read more about "package discovery" on setuptools documentation page:

          - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

          If you don't want 'grss.debias' to be distributed and are
          already explicitly excluding 'grss.debias' via
          `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
          you can try to use `exclude_package_data`, or `include-package-data=False` in
          combination with a more fine grained `package-data` configuration.

          You can read more about "package data files" on setuptools documentation page:

          - https://setuptools.pypa.io/en/latest/userguide/datafiles.html


          [^1]: For Python, any directory (with suitable naming) can be imported,
                even if it does not contain any `.py` files.
                On the other hand, currently there is no concept of package data
                directory, all directories are treated like packages.
          ********************************************************************************

  !!
    check.warn(importable)
  /tmp/pip-build-env-an6mypj5/overlay/lib/python3.9/site-packages/setuptools/command/build_py.py:207: _Warning: Package 'grss.kernels' is absent from the `packages` configuration.
  !!

          ********************************************************************************
          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'grss.kernels' as an importable package[^1],
          but it is absent from setuptools' `packages` configuration.

          This leads to an ambiguous overall configuration. If you want to distribute this
          package, please make sure that 'grss.kernels' is explicitly added
          to the `packages` configuration field.

          Alternatively, you can also rely on setuptools' discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).

          You can read more about "package discovery" on setuptools documentation page:

          - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

          If you don't want 'grss.kernels' to be distributed and are
          already explicitly excluding 'grss.kernels' via
          `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
          you can try to use `exclude_package_data`, or `include-package-data=False` in
          combination with a more fine grained `package-data` configuration.

          You can read more about "package data files" on setuptools documentation page:

          - https://setuptools.pypa.io/en/latest/userguide/datafiles.html


          [^1]: For Python, any directory (with suitable naming) can be imported,
                even if it does not contain any `.py` files.
                On the other hand, currently there is no concept of package data
                directory, all directories are treated like packages.
          ********************************************************************************

  !!
    check.warn(importable)
  copying grss/version.txt -> build/lib.linux-x86_64-cpython-39/grss
  creating build/lib.linux-x86_64-cpython-39/grss/debias
  copying grss/debias/get_debiasing_data.py -> build/lib.linux-x86_64-cpython-39/grss/debias
  creating build/lib.linux-x86_64-cpython-39/grss/kernels
  copying grss/kernels/create_kernel_431.txt -> build/lib.linux-x86_64-cpython-39/grss/kernels
  copying grss/kernels/create_kernel_441.txt -> build/lib.linux-x86_64-cpython-39/grss/kernels
  copying grss/kernels/get_kernels.py -> build/lib.linux-x86_64-cpython-39/grss/kernels
  copying grss/kernels/pck00011.tpc -> build/lib.linux-x86_64-cpython-39/grss/kernels
  copying grss/kernels/planets_big16_de431_1950_2350.log -> build/lib.linux-x86_64-cpython-39/grss/kernels
  copying grss/kernels/planets_big16_de431_1950_2350.tm -> build/lib.linux-x86_64-cpython-39/grss/kernels
  copying grss/kernels/planets_big16_de441_1950_2350.log -> build/lib.linux-x86_64-cpython-39/grss/kernels
  copying grss/kernels/planets_big16_de441_1950_2350.tm -> build/lib.linux-x86_64-cpython-39/grss/kernels
  running build_ext
  ./build_cpp.sh: line 31: cmake: command not found
  make: *** No targets specified and no makefile found.  Stop.
  cp: cannot stat '/home/mthui/Software/grss/grss/build/prop_simulation*': No such file or directory
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/grss
  creating build/bdist.linux-x86_64/wheel/grss/fit
  copying build/lib.linux-x86_64-cpython-39/grss/fit/fit_radar.py -> build/bdist.linux-x86_64/wheel/grss/fit
  copying build/lib.linux-x86_64-cpython-39/grss/fit/fit_optical.py -> build/bdist.linux-x86_64/wheel/grss/fit
  copying build/lib.linux-x86_64-cpython-39/grss/fit/fit_utils.py -> build/bdist.linux-x86_64/wheel/grss/fit
  copying build/lib.linux-x86_64-cpython-39/grss/fit/fit_simulation.py -> build/bdist.linux-x86_64/wheel/grss/fit
  copying build/lib.linux-x86_64-cpython-39/grss/fit/__init__.py -> build/bdist.linux-x86_64/wheel/grss/fit
  copying build/lib.linux-x86_64-cpython-39/grss/version.txt -> build/bdist.linux-x86_64/wheel/grss
  creating build/bdist.linux-x86_64/wheel/grss/kernels
  copying build/lib.linux-x86_64-cpython-39/grss/kernels/pck00011.tpc -> build/bdist.linux-x86_64/wheel/grss/kernels
  copying build/lib.linux-x86_64-cpython-39/grss/kernels/create_kernel_431.txt -> build/bdist.linux-x86_64/wheel/grss/kernels
  copying build/lib.linux-x86_64-cpython-39/grss/kernels/create_kernel_441.txt -> build/bdist.linux-x86_64/wheel/grss/kernels
  copying build/lib.linux-x86_64-cpython-39/grss/kernels/get_kernels.py -> build/bdist.linux-x86_64/wheel/grss/kernels
  copying build/lib.linux-x86_64-cpython-39/grss/kernels/planets_big16_de441_1950_2350.log -> build/bdist.linux-x86_64/wheel/grss/kernels
  copying build/lib.linux-x86_64-cpython-39/grss/kernels/planets_big16_de431_1950_2350.log -> build/bdist.linux-x86_64/wheel/grss/kernels
  copying build/lib.linux-x86_64-cpython-39/grss/kernels/planets_big16_de431_1950_2350.tm -> build/bdist.linux-x86_64/wheel/grss/kernels
  copying build/lib.linux-x86_64-cpython-39/grss/kernels/planets_big16_de441_1950_2350.tm -> build/bdist.linux-x86_64/wheel/grss/kernels
  creating build/bdist.linux-x86_64/wheel/grss/debias
  copying build/lib.linux-x86_64-cpython-39/grss/debias/get_debiasing_data.py -> build/bdist.linux-x86_64/wheel/grss/debias
  creating build/bdist.linux-x86_64/wheel/grss/prop
  copying build/lib.linux-x86_64-cpython-39/grss/prop/prop_unscented.py -> build/bdist.linux-x86_64/wheel/grss/prop
  copying build/lib.linux-x86_64-cpython-39/grss/prop/prop_utils.py -> build/bdist.linux-x86_64/wheel/grss/prop
  copying build/lib.linux-x86_64-cpython-39/grss/prop/prop_parallel.py -> build/bdist.linux-x86_64/wheel/grss/prop
  copying build/lib.linux-x86_64-cpython-39/grss/prop/__init__.py -> build/bdist.linux-x86_64/wheel/grss/prop
  copying build/lib.linux-x86_64-cpython-39/grss/__init__.py -> build/bdist.linux-x86_64/wheel/grss
  copying build/lib.linux-x86_64-cpython-39/grss/utils.py -> build/bdist.linux-x86_64/wheel/grss
  running install_egg_info
  Copying grss.egg-info to build/bdist.linux-x86_64/wheel/grss-3.0.0-py3.9.egg-info
  running install_scripts
  creating build/bdist.linux-x86_64/wheel/grss-3.0.0.dist-info/WHEEL
  creating '/tmp/pip-wheel-c_yoja_4/.tmp-5p5wehhq/grss-3.0.0-cp39-cp39-linux_x86_64.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
  adding 'grss/__init__.py'
  adding 'grss/utils.py'
  adding 'grss/version.txt'
  adding 'grss/debias/get_debiasing_data.py'
  adding 'grss/fit/__init__.py'
  adding 'grss/fit/fit_optical.py'
  adding 'grss/fit/fit_radar.py'
  adding 'grss/fit/fit_simulation.py'
  adding 'grss/fit/fit_utils.py'
  adding 'grss/kernels/create_kernel_431.txt'
  adding 'grss/kernels/create_kernel_441.txt'
  adding 'grss/kernels/get_kernels.py'
  adding 'grss/kernels/pck00011.tpc'
  adding 'grss/kernels/planets_big16_de431_1950_2350.log'
  adding 'grss/kernels/planets_big16_de431_1950_2350.tm'
  adding 'grss/kernels/planets_big16_de441_1950_2350.log'
  adding 'grss/kernels/planets_big16_de441_1950_2350.tm'
  adding 'grss/prop/__init__.py'
  adding 'grss/prop/prop_parallel.py'
  adding 'grss/prop/prop_unscented.py'
  adding 'grss/prop/prop_utils.py'
  adding 'grss-3.0.0.dist-info/LICENSE'
  adding 'grss-3.0.0.dist-info/METADATA'
  adding 'grss-3.0.0.dist-info/WHEEL'
  adding 'grss-3.0.0.dist-info/top_level.txt'
  adding 'grss-3.0.0.dist-info/RECORD'
  removing build/bdist.linux-x86_64/wheel
  Building wheel for grss (pyproject.toml) ... done
  Created wheel for grss: filename=grss-3.0.0-cp39-cp39-linux_x86_64.whl size=83993 sha256=172885fadbdea152dd03787e9b9a9f236acea65769d8fe5893438c52d9b63c79
  Stored in directory: /tmp/pip-ephem-wheel-cache-83ux4ark/wheels/bb/ba/da/a1bac8650486420073ab3e8009882b6f68de49325817e66324
Successfully built grss
Installing collected packages: grss
Successfully installed grss-3.0.0
```
I'm wondering if that error about the incompatibility of clyent matters. But if it does the installation won't be successful.

**Comment by Pachacoti** [comment]
I completely overlooked these extracted lines from the above lengthy output:
```
  ./build_cpp.sh: line 31: cmake: command not found
  make: *** No targets specified and no makefile found.  Stop.
  cp: cannot stat '/home/mthui/Software/grss/grss/build/prop_simulation*': No such file or directory
```
This looks like the real culprit for causing the problem.

**Comment by rahil-makadia** [comment]
Okay I think I see the issue. Looks like your machine does not have cmake installed (you can get this using your default Linux package manager). GRSS uses cmake to generate platform-independent makefiles for building the C++ binaries.

The quickest fix would be to install cmake on your machine and then reinstall grss either using pip or from source (it might be worth pulling from the repo again since I've pushed updates while we've been talking)

**Comment by rahil-makadia** [comment]
Although I used to ship python wheels for different Linux and Mac systems in an older version for GRSS. Might be worth revisiting that when I get the time...

**Comment by rahil-makadia** [comment]
My apologies that the install itself has been a pain. But if you still have issues after installing cmake, definitely let me know.

**Comment by rahil-makadia** [comment]
Glad to hear this! Yeah, I think I'll add a check to confirm that the pybind11 binary was created during install to avoid this in the future. Closing this issue for now!

**Comment by rahil-makadia** [comment]
Glad to hear this! Yeah, I think I'll add a check to confirm that the pybind11 binary was created during install to avoid this in the future. Closing this issue for now!
