### ISSUE TITLE
singular optical covariance matrix

### ISSUE THREAD

**Issue by Pachacoti** [rahil-makadia/grss#78]
The following error is encountered when I tried to run
```
>>> fit_sim = fit.FitSimulation(init_sol, obs_df, init_cov, n_iter_max=n_iter_max, de_kernel=de_kernel, nongrav_info=nongrav_info)
```
for Apophis:
```
[[ 4.0e-08 -8.0e-08]
 [-8.0e-08  1.6e-07]]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mthui/Software/anaconda3/envs/grss/lib/python3.12/site-packages/grss/fit/fit_simulation.py", line 549, in __init__
    self._compute_obs_weights()
  File "/home/mthui/Software/anaconda3/envs/grss/lib/python3.12/site-packages/grss/fit/fit_simulation.py", line 772, in _compute_obs_weights
    raise ValueError("Optical covariance matrix is singular.")
ValueError: Optical covariance matrix is singular.
```

**Comment by rahil-makadia** [comment]
I took a look, and it seems that Apophis has an observation with perfect correlation in the observation database, which leads to a singular observation covariance. I would just remove that observation from the dataframe for now

**Comment by rahil-makadia** [comment]
I'm gonna go ahead and close this issue since there isn't anything I can do about that measurement from the GRSS side...
